{% set name = "argopy" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88e550e4b6d09c0d7e234274cc40dea4f124103e33f1f306a0b33e64fc5fbe57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - dask >=2.9
    - erddapy >=0.5,<0.8.0
    - fsspec >=0.7.1
    - gsw >=3.3.1
    - ipython >=5.0.0
    - netcdf4 >=1.3.1
    - numpydoc >=0.6.0
    - scikit-learn >=0.21
    - scipy >=1.1.0
    - toolz >=0.8.2
    - xarray >=0.14

test:
  imports:
    - argopy
    - argopy.data_fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
