{% set name = "argopy" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18cdffd9e1f5837f8ae5a50ea380ea9964dfaf3c1a0b31fe8f0b5c5cb8ef8da9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp >=3.6.2,<3.8.2
    - dask-core >=2.9,<2022.1.1
    - erddapy >=0.6,<1.2.1
    - fsspec >=0.7.4,<2022.2.0
    - gsw <=3.4.0,>=3.3.1
    - netcdf4 <1.5.9,>=1.3.1
    - packaging >=20.4,<22.0
    - scikit-learn <2.0,>=0.21
    - scipy >=1.1.0,<1.7.4
    - toolz >=0.8.2,<0.11.3
    - xarray >=0.15.1,<0.20.3

test:
  imports:
    - argopy
    - argopy.data_fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
