{% set name = "argopy" %}
{% set version = "0.1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41baa3dd92b298562ec51a52bacc37956e6b286b8d1e77fb2b39e3c170a3c1f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - pip
  run:
    - python >=3.6
    - xarray >=0.16
    - scipy >=1.5
    - netcdf4 >=1.5.3
    - toolz >=0.8.2
    - erddapy >=0.7
    - fsspec >=0.8
    - aiohttp >=3.7
    - packaging >=20.4
    # imports pkg_resources
    - setuptools >=42
    # extras
    - dask-core >=2.3
    - gsw <=3.4.0
    - scikit-learn >=0.23

test:
  imports:
    - argopy
    - argopy.data_fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
