{% set name = "argopy" %}
{% set version = "0.1.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/euroargodev/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7d12251b59304fe3289a861225317876f2762c22607719515ea889aa65dd02ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - pip
  run:
    - netcdf4 >=1.5.3
    - python >=3.7
    - aiohttp >=3.7
    - erddapy >=0.7
    - fsspec >=0.8
    - netCDF4 >=1.5.3
    - packaging >=20.4
    - requests >=2.28
    - scipy >=1.5
    - toolz >=0.8.2
    - xarray >=0.18
    # imports pkg_resources
    - setuptools >=42

test:
  imports:
    - argopy
    - argopy.data_fetchers

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
