{% set name = "argopy" %}
{% set version = "0.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5af0a2cc0805e3e7c599b3b4e7cded86c39da06eafa0270fb410bf7fa06e08ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - aiohttp <3.8.1,>=3.6.2
    - dask-core <2021.10.1,>=2.9
    - erddapy <=1.1.1,>=0.6
    - fsspec <=2021.10.0,>=0.7.4
    - gsw <=3.4.0,>=3.3.1
    - netcdf4 <1.5.9,>=1.3.1
    - packaging >=20.4,<22.0
    - scikit-learn <2.0,>=0.21
    - scipy <=1.7.1,>=1.1.0
    - toolz <=0.11.1,>=0.8.2
    - xarray <=0.19.0,>=0.15.1

test:
  imports:
    - argopy
    - argopy.data_fetchers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
